#include <Windows.h>
#include <windowsx.h>
#include <string>
#include <chrono>
#include <thread>
#include <Psapi.h>
#include <map>
#include <vector>
#include <d3d9.h>
#include <d3dx9.h>

#include "../console/console.hh"
#include "../source_development_kit/math/vector/vector2d.hh"
#include "../source_development_kit/math/vector/vector3d.hh"
#include "../source_development_kit/math/matrix/matrix3x4.hh"
#include "../source_development_kit/math/math.hh"
#include "../render/fonts/fonts.hh"
#include "../render/render.hh"
#include "../source_development_kit/utilities/utilities.hh"
#include "../source_development_kit/valve/recv.hh"
#include "../netvar_manager/netvar_manager.hh"
#include "../source_development_kit/valve/c_client.hh"
#include "../source_development_kit/valve/iv_engine_client.hh"
#include "../source_development_kit/valve/i_input_system.hh"
#include "../source_development_kit/valve/i_surface.hh"
#include "../source_development_kit/interfaces/interfaces.hh"
#include "../source_development_kit/hooker/hooker.hh"
#include "../source_development_kit/memory/memory.hh"
#include "../hook_manager/hook_manager.hh"
#include "../silentgui/menu_helpers/menu_helpers.hh"
#include "../silentgui/silentgui.hh"